# baseURL = "http://levell.tech/~patrick"
baseURL = "http://levell.tech"
languageCode = "en-us"
title = "Hugo & Tailwind 3.0"
disableKinds = ["taxonomy","taxonomyTerm"]

[markup.goldmark.renderer]
    unsafe = true



